# Generated by Django 5.0.7 on 2024-07-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='Место')),
                ('time', models.DateTimeField(max_length=25, verbose_name='Время, когда надо выполнить привычку')),
                ('action', models.CharField(max_length=100, verbose_name='Действие, которое надо сделать')),
                ('duration', models.SmallIntegerField(verbose_name='Продолжительность в минутах')),
                ('is_daily', models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=True, help_text='True: Раз в день, False: раз в неделю', verbose_name='Периодичность')),
                ('is_good', models.BooleanField(choices=[(True, 'Приятная'), (False, 'Нет')], default=True, verbose_name='Приятная')),
                ('is_public', models.BooleanField(choices=[(True, 'Публичная'), (False, 'Нет')], default=True, verbose_name='Публичная')),
                ('prize', models.CharField(blank=True, max_length=100, null=True, verbose_name='Награда')),
                ('mailing_sign', models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак рассылки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['-id'],
            },
        ),
    ]
