# Generated by Django 5.0.7 on 2024-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='prize',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Награда'),
        ),
    ]
