# Generated by Django 5.0.7 on 2024-07-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habits_prize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='is_daily',
            field=models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=True, verbose_name='Периодичность'),
        ),
    ]
