# Generated by Django 5.0.7 on 2024-07-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_is_daily'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='is_daily',
            field=models.BooleanField(choices=[(True, 'Ежедневная'), (False, 'Еженедельная')], default=True, help_text='True: Раз в день, False: раз в неделю', verbose_name='Периодичность'),
        ),
    ]
