# Generated by Django 5.0.7 on 2024-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_is_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='mailing_sign',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Признак рассылки'),
        ),
    ]
